version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: todo_app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data: