import ProfileButton from './components/profile';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <ProfileButton />
        {children}
      </body>
    </html>
  )
}
