import ProfileButton from "./components/profile";
import { TRPCProvider } from '@/utils/trpcProvider';

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<body>
				<TRPCProvider>
					<ProfileButton />
					{children}
				</TRPCProvider>
			</body>
		</html>
	);
}
